project:
  type: book
  output-dir: docs

book:
  title: "Applied Mechanics Workbook"
  subtitle: "Supplementary Exercises for In-Class Learning"
  author: "Serhat Beyenir"
  date: today
  date-format: "MMMM D, YYYY"
  cover-image: images/cover.png
  downloads: [pdf]
  page-footer:
    left: |
      © 2024 <a href="https://creativecommons.org/licenses/by-nc/4.0/">CC BY-NC 4.0</a>
    right: |
      Built with <a href="https://quarto.org"> Quarto</a>
  chapters:
    - index.qmd
    - SI_Units.qmd
    - scalar-and-vector-quantities.qmd
    - kinematics.qmd
    - moment-of-a-force.qmd
    - review.qmd
    - references.qmd
    
bibliography: references.bib

format:
  html:
    theme:
      light: cosmo #flatly
      dark: solar
  pdf:
    #latex-engine: xelatex  # or pdflatex, if preferred
    documentclass: book #scrreprt
    toc-title: Contents
    lot: true
    lof: true
    include-in-header: 
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body: 
      text: |
        \printindex

editor: visual


<!--geometry:
  - left=.75in
  - textwidth=4.5in
  - marginparsep=.25in
  - marginparwidth=2.5in-->

