project:
  type: book
  output-dir: docs

book:
  title: "Applied Mechanics Workbook"
  subtitle: "Supplementary Exercises for In-Class Learning"
  author: "Serhat Beyenir"
  date: "2024-11-06"
  date-format: "MMMM D, YYYY"
  cover-image: /images/cover.png
  downloads: [pdf]
  page-footer:
    left: |
      © 2024 <a href="https://creativecommons.org/licenses/by-nc/4.0/">CC BY-NC 4.0</a>
    right: |
      Built with <a href="https://quarto.org"> Quarto</a>
  chapters:
    - index.qmd
    - SI_Units.qmd
    - scalar-and-vector-quantities.qmd
    - moment-of-a-force.qmd
    - summary.qmd
    - references.qmd
    
bibliography: references.bib

format:
  html:
    theme:
      light: flatly
      dark: solar
  pdf:
    toc-title: Contents
    lof: true
    lot: true
    documentclass: book #scrbook
    classoption: [paper=letterpaper]
    include-in-header: 
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body: 
      text: |
        \printindex

<!--geometry:
  - left=.75in
  - textwidth=4.5in
  - marginparsep=.25in
  - marginparwidth=2.5in-->
  
editor: visual

